### ISSUE TITLE
Extension is moving elements down

### ISSUE THREAD

**Issue by enzon19** [duffey/spicetify-playlist-labels#1]
![image](https://github.com/duffey/spicetify-playlist-labels/assets/89558747/4e00d611-1352-4d9e-854e-5c68548fbad0)

I don't know if this is because I have other extensions installed (like the stars rating), but now that I installed Playlist Labels, all the buttons and elements on the playlist have moved down. I really want to use this extension because it's useful, but this way is impossible.

**Comment by duffey** [comment]
It's very likely because the star rating extension adds a column to the tracklist just like this extension does. I did not write them to be compatible, but rather wrote this one to be a replacement. I will think about if I can fix this, but I'm not very motivated to continue working on the star rating extension as I no longer use it. If I can do it easily I might.
