### ISSUE TITLE
Extension borderline unusable with slow internet speed

### ISSUE THREAD

**Issue by SirSragus** [duffey/spicetify-playlist-labels#22]
Does this extension need to reupload and then download playlist art to function?

When I attempt to use this extension my network usage for Spotify on Resource Monitor displays ~90,000 B/sec (both Upload and Download), which is around my max upload speed.

I used this extension for a bit when Star Ratings was first archived and it worked (love the idea btw), but caused noticeable slowdowns so I stopped using it and switched back to a fork of Star Ratings.
I just tried using the extension again and after 7 minutes of my internet being crippled from the upload, Spotify ended up refreshing (like when installing a new extension and reloading), but the labels still hadn't loaded in yet.

I do have more playlists now so that is probably why it seems much slower, but with or without the additional playlists I don't know that I'd be able to use this extension as is with my internet speed.

Just wondering if there was any way for this to be handled locally, or if there is some other issue.

If not, that's unfortunate, but no worries.

**Comment by duffey** [comment]
This extension does not make any explicit requests for playlist art. Since it does display playlist art for the labels, a request is made anytime new playlist art is displayed, but then the image is cached.

Regarding API requests, this extension downloads all playlist data when it first starts, as does the Star Ratings extension.

https://github.com/duffey/spicetify-playlist-labels/blob/355bfabdfd68d3a98460d8e44b9bd0f9fe3d1fe9/src/app.tsx#L168

The only time it makes another API request is in response to "update"" events. This is to detect when a track is removed or added to a playlist in a way the script couldn't otherwise know about.

https://github.com/duffey/spicetify-playlist-labels/blob/355bfabdfd68d3a98460d8e44b9bd0f9fe3d1fe9/src/app.tsx#L149-L155

I'm not sure what could be causing the issue, but I did notice that Spicetify makes a lot of requests when Marketplace is installed. I suggest installing Spicetify without Marketplace to see if that has any effect. Also, if you do that, then open Dev Tools and look at the Network tab to see what is being downloaded. That would really help me figure out what your issue is.

**Comment by duffey** [comment]
@SirSragus 
Hey, I just got a similar report here: https://github.com/duffey/spicetify-playlist-labels/issues/23

I added a bunch of caching which might solve the issue for you. Please let me know once it's updated if it's any faster.

**Comment by SirSragus** [comment]
Well, I've had the extension installed again for a couple hours without my original network issue.

However, the labels haven't appeared this entire time, though the space for them is there.

**Comment by duffey** [comment]
I intend to fix this by using IndexedDB to cache information.

**Comment by duffey** [comment]
I just pushed a new update. Please let me know if it works!

**Comment by SirSragus** [comment]
I am able to get the labels to load now, the issue with the network load seems to have improved. However, the responsiveness for me is still as described in #23.

**Comment by SirSragus** [comment]
These fixes seem to have improved performance significantly. Extension is definitely usable today.

**Comment by duffey** [comment]
What order do you expect them to be in? I don't do any sorting.

**Comment by SirSragus** [comment]
Ooh, ok. I figured they'd be sorted in the order they are in the library. For some reason it seems to load that way at first, then they just go random after a while.

**Comment by duffey** [comment]
Maybe I should sort them by date-added.

**Comment by duffey** [comment]
Responsiveness has been improved by relying on cached data, but it can be a bit further optimized still. I'm going to make a separate issue.
